server:
  #端口
  port: 8082

spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: DUn3Wn3YqN2nYbt6  #填写实际申请的授权码
    username: 13662732185@163.com #填写实际申请的邮箱
    port: 25
  rabbitmq:
    username: guest
    password: guest
    #服务器地址
    host: localhost
    #端口
    port: 5672
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

  redis:
    #服务器地址
    host: localhost
    #服务器端口
    port: 6379
    password: 123456
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间，默认为-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接数
        min-idle: 5

